easy_admin:
    site_name: "Site d'annonce"
    design:
        brand_color: '#1ABC9C'
        form_theme: '@EasyAdmin/form/bootstrap_4.html.twig'
    entities:
        # List the entity class name you want to manage
        Advert:
            class: App\Entity\Advert
            label: 'Annonces'
            list:
                title: "La liste des %%entity_label%%"
                max_results: 10
                sort: ['date', 'ASC']
        Application:
            class: App\Entity\Application
            label: 'Les candidatures'
            list:
                title: "Les candidatures"
        Category:
            class: App\Entity\Category
            label: 'Les categories'
            list:
                 title: "Les categories"
        Users:
            class: App\Entity\User
            label: 'La list des utilisateurs'
            list:
                 title: "Les utilisateurs"
        Images:
            class: App\Entity\Image
            label: 'La list des images'
            list:
                 title: "Les images"