easy_admin:
    site_name: "Site d'annonce"
    design:
        brand_color: '#1ABC9C'
        form_theme: '@EasyAdmin/form/bootstrap_4.html.twig'
        menu:
            - { entity: 'User', css_class: 'default', target: '_parent'  }
            - { entity: 'Advert', icon: 'id-card-o'}
            - { entity: 'Advert', icon: 'phone'}
            - { entity: 'Advert', icon: 'thermometer-2'}
            - { entity: 'Advert', icon: 'leaf'}
            - { entity: 'Advert', icon: 'th-list'}
            - { entity: 'Category', icon: 'sticky-note' } #sans icon
            - { entity: 'Images', label: 'Tags', icon: 'tag'  }
            - { label: 'Some Task', route: 'home' }
            - label: 'Clients'
              children: ['Category', 'Images', 'User', 'Advert']
            - label: 'Users'
              icon: 'users'
              children:
              - { label: 'Admin', icon: 'exclamation', route: 'home' }
              - { label: 'User', icon: 'paw', entity: 'Images' }
              - { label: 'Entreprise', icon: 'pencil', entity: 'Advert' }
            - {label: 'aaa', icon: ''}
    list:
        actions:
            - { name: 'search', icon: 'search', label: 'Search' }
            - { name: 'new', icon: 'add', label: 'New' }
            - { name: 'edit', icon: 'edit', label: 'Edit' }
            - { name: 'delete', icon: 'delete', label: 'Delete' }
            - { name: 'show', icon: 'info-circle', label: '' }
    entities:
        # List the entity class name you want to manage
        Advert:
            class: App\Entity\Advert
            label: 'Annonces'
            list:
                title: "La liste des %%entity_label%%"
                max_results: 20
                sort: ['date', 'ASC']
                actions:
                    - { name: 'edit', icon: 'pencil', label: 'Edit' }
        Application:
            class: App\Entity\Application
            label: 'Les candidatures'
            list:
                title: "Les candidatures"
        Category:
            class: App\Entity\Category
            label: 'Les categories'
            list:
                 title: "Les categories"
        User:
            class: App\Entity\User
            label: 'La list des utilisateurs'
            list:
                 title: "Les utilisateurs"
        Images:
            class: App\Entity\Image
            label: 'La list des images'
            list:
                 title: "Les images"