easy_admin:
    site_name: "Site d'annonce"
    design:
        brand_color: '#1ABC9C'
        form_theme: '@EasyAdmin/form/bootstrap_4.html.twig'
        menu:
            - { entity: 'UserAdmin', css_class: 'default', target: '_parent'  }
            - { entity: 'Advert', icon: 'id-card-o'}
            - { entity: 'Advert', icon: 'phone'}
            - { entity: 'Advert', icon: 'thermometer-2'}
            - { entity: 'Advert', icon: 'leaf'}
            - { entity: 'Advert', icon: 'th-list'}
            - { entity: 'Category', icon: 'sticky-note' } #sans icon
            - { entity: 'Images', label: 'Images', icon: 'image'  }
            - { label: 'Some Task', route: 'home' }
            - { label: 'Dashboard', route: 'home'}
            - label: 'Users'
              icon: 'users'
              children:
              - { label: 'Admin', icon: 'user-secret', entity: 'UserAdmin' }
              - { label: 'User', icon: 'user', entity: 'UserSimple' }
              - { label: 'Entreprise', icon: 'address-book', entity: 'UserEntreprise' }
            - {label: 'aaa', icon: ''}
    list:
        actions:
            - { name: 'search', icon: 'search', label: 'search' }
            - { name: 'new', icon: 'plus-circle', label: 'New' }
            - { name: 'edit', icon: 'edit', label: '' }
            - { name: 'delete', icon: 'trash', label: '' }
            - { name: 'show', icon: 'eye', label: '' }
    entities:
        # List the entity class name you want to manage
        Advert:
            class: App\Entity\Advert
            label: 'Annonces'
            list:
                title: "La liste des %%entity_label%%"
                max_results: 20
                sort: ['date', 'ASC']
        Application:
            class: App\Entity\Application
            label: 'Les candidatures'
            list:
                title: "Les candidatures"
        Category:
            class: App\Entity\Category
            label: 'Les categories'
            list:
                 title: "Les categories"
        UserAdmin:
            class: App\Entity\User
            #controller: AppBundle\Entity\admin\AdminController
            label: 'La list des utilisateurs'
            list:
                 title: "Les utilisateurs"
                 dql_filter: "entity.roles = 'ROLE_ADMIN' "
                 #- { property: 'purposes', type_options: { query_builder: ['Bundle\Repository\EasyAdmin\SomeRepo', 'getAccessible'] } }
        UserSimple:
            class: App\Entity\User
            list:
                 #dql_filter: 'entity.roles = ""'
        UserEntreprise:
            class: App\Entity\User
            list:
                 #ql_filter: 'entity.roles = ROLE_USER_Entreprise'
        Images:
            class: App\Entity\Image
            label: 'La list des images'
            list:
                 title: "Les images"